# Generated by Django 2.1 on 2021-08-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210814_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceBankReco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('finance_bank_recon_all', 'Access to all features'),),
            },
        ),
    ]
