# Generated by Django 2.2.10 on 2022-03-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_financebankreco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comany_id', models.TextField()),
                ('company_name', models.TextField()),
            ],
            options={
                'unique_together': {('comany_id', 'company_name')},
            },
        ),
    ]
