# Generated by Django 2.2.10 on 2022-03-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Companies',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='comany_id',
            new_name='company_id',
        ),
        migrations.AlterUniqueTogether(
            name='companies',
            unique_together={('company_id', 'company_name')},
        ),
    ]
