# Generated by Django 2.2.10 on 2022-03-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220329_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('company_id', 'company_name'), 'verbose_name_plural': 'Companies'},
        ),
    ]
