# Generated by Django 2.2.10 on 2022-03-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220329_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.TextField()),
                ('user_id', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'UserCompanyAssignments',
                'ordering': ('company_id', 'user_id'),
                'unique_together': {('company_id', 'user_id')},
            },
        ),
    ]
