# Generated by Django 2.2.10 on 2022-03-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_usercompanyassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompanyassignment',
            name='company_id',
            field=models.CharField(choices=[('BDC', 'BDC'), ('WFC', 'WFC')], max_length=256),
        ),
    ]
