# Generated by Django 3.2.13 on 2023-02-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220330_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompanyassignment',
            name='company_id',
            field=models.CharField(choices=[('BDC', 'BDC'), ('WFC', 'WFC'), ('GWC', 'GWC'), ('TST', 'TST'), ('GMC', 'GMC'), ('TST2', 'TST2'), ('QA', 'QA')], max_length=256),
        ),
    ]
