from openpyxl import load_workbook
from openpyxl.styles.alignment import Alignment
import pymongo
from .random_string_generator import RandomString_Generator as rand_gen
### test run below
# from sample_entries import samples
# sample_entries, sample_PB_data, sample_GL_data = samples()

client = pymongo.MongoClient(host='localhost', port=27017)

class AJE_sheet():
    def __init__(self, filename: str):
        self.wb = load_workbook('/home/admin/apps/bank_recon'
                                +'/development/recon/app/controllers'
                                +'/helpers/aje_export_module/'
                                +'excel_files/file_format.xlsx')
        self.ws = self.wb["Form"]
        self.output_filename = ('/home/admin/apps/bank_recon'
                                +'/development/recon/app/controllers'
                                +'/helpers/aje_export_module/'
                                +f'output/{filename}')
    
    def insert_data_on_cell(self, cell_code: str, data: str) -> None:
        self.ws[cell_code] = data
        self.ws[cell_code].alignment = Alignment(
                                        horizontal='center',
                                        vertical='center')
    
    def save(self) -> None:
        self.wb.save(self.output_filename)


class Entry_Formatter:
    def __init__(self, xentry, type_of_list):
        self.type_of_list = type_of_list
        self._id = xentry["_id"]
        self.transaction_date = (xentry["transaction_date"]
                                    if type_of_list == "PB"
                                    else xentry["trndate"])
        self.transaction_code = (xentry['transaction_description']
                                    if type_of_list == "PB"
                                    else xentry['ref_2'])
        self.debit_amount = ((xentry['debit_amount']
                                if xentry['debit_amount']
                                else float(0)) 
                                if type_of_list == "PB"
                                else (xentry['dr_amt']
                                    if xentry['dr_amt']
                                    else float(0)))
        self.credit_amount = ((xentry['credit_amount']
                                if xentry['credit_amount']
                                else float(0))
                                if type_of_list == "PB"
                                else (xentry['cr_amt']
                                    if xentry['cr_amt']
                                    else float(0)))

    #  test this
    def get_dict_and_keys(self, company_code):
        db = client[f'{company_code}_AJE_records']
        pb_draft = db['pb_aje_draft']
        gl_draft = db["gl_aje_draft"]
        entry = {
            "type_of_list" : self.type_of_list,
            "original_id" : self._id,
            "transaction_date" : self.transaction_date,
            "transaction_code" : self.transaction_code,
            "debit_amount" : self.debit_amount,
            "credit_amount" : self.credit_amount,
            "transaction_number" : "",
            "adjustment_type_code" : "",
            "description" : "",
            "recon" : 0
        }
        # id_inserted = col.insert_one(entry).inserted_id
        entry["transaction_aje_number"] = rand_gen.generate_AJE_Number(self._id)
        (pb_draft.update_one({"original_id": self._id}, {"$setOnInsert": entry}, upsert=True)
         if self.type_of_list == "PB"
         else gl_draft.update_one({"original_id": self._id}, {"$setOnInsert": entry}, upsert=True))
        entry.pop("original_id")
        # entry.pop("_id")
        entry.pop("type_of_list")
        keys = list(entry.keys())
        return entry, keys
    
    def get_column_code(self, key, current_row):
        column_letter = {
            "transaction_date" : "A",	
            "transaction_aje_number" : "B",#will be generated by the system
            "transaction_code" : "C",
            "debit_amount" : 'D',
            "credit_amount" : 'E',
            "transaction_number" : "F",
            "adjustment_type_code" : "G",
            "description" : "H",
            "recon" : "I"
        }
        column_code = column_letter[key]
        if key == 'transaction_description':
            column_code = column_letter['transaction_code']
        cell_code = f"{column_code}{current_row}"
        return cell_code

#  test this
def create_sheet(sheetname, entries, type_of_list, company_code):
    current_row = 4
    aje = AJE_sheet(sheetname)
    for xentry in entries:
        entry_form = Entry_Formatter(xentry, type_of_list)
        entry, keys = entry_form.get_dict_and_keys(company_code)
        for key in keys:
            cell_code = entry_form.get_column_code(key, current_row)
            value = entry[key]
            aje.insert_data_on_cell(cell_code, value)
        current_row+=1
    aje.save()

def generate_aje_filename(type_of_list):
    aje_filename = rand_gen.get_random_filename(type_of_list)
    return aje_filename

### Test run below
# type_of_list = "GL"
# aje_filename = generate_aje_filename(type_of_list)
# create_sheet(aje_filename, sample_GL_data, type_of_list)


# type_of_list = "PB"
# aje_filename = generate_aje_filename(type_of_list)
# create_sheet(aje_filename, sample_PB_data, type_of_list)